import { Box, Button, Paper, Typography } from '@mui/material';
import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
const inter = Inter({ subsets: ['latin'] });

function Confirmation() {
    const [data, setData] = useState('');
    const [error, setError] = useState(false);
    const router = useRouter();
    useEffect(() => {
        setError(false);
        async function fetchData() {
            try {
                if (!router.isReady) {
                    return;
                }
                const { confirmation } = router.query;
                const result = await axios({
                    method: 'get',
                    url: `http://localhost:3001/profil/verify/${confirmation}`,
                });
                setData(result);
            } catch (e) {
                console.log(e);
                setError(true);
            }
        }
        fetchData();
    }, [router.isReady]);

    return (
        <>
            <Head>
                <title>Confirmer son email</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Paper
                    sx={{
                        padding: 20,
                        display: 'flex',
                        flexDirection: 'column',
                        justifyContent: 'center',
                        alignItems: 'center',
                    }}
                >
                    <Box
                        sx={{
                            display: 'flex',
                            flexDirection: 'column',
                            justifyContent: 'center',
                            alignItems: 'center',
                        }}
                    >
                        <h1>
                            {error
                                ? 'Sorry...😅'
                                : 'Compte confirmé et validé!'}
                        </h1>
                        <Box
                            sx={{
                                backgroundColor: '#BA55D3',
                                width: 110,
                                height: 5,
                                marginBottom: 2,
                                marginTop: 1,
                            }}
                        ></Box>
                        <Typography>
                            {error
                                ? 'On a un problème avec votre email. Veuillez vous réinscrire.'
                                : "Il ne te reste plus qu'à te connecter.😉"}
                        </Typography>
                    </Box>

                    <Link href="/">
                        <Button color="secondary">Page d'accueil</Button>
                    </Link>
                </Paper>
            </main>
        </>
    );
}
export default Confirmation;
